"""Changed datetime to date

Revision ID: 59406947947f
Revises: 2b7d524c9687
Create Date: 2021-09-11 16:13:13.921329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59406947947f'
down_revision = '2b7d524c9687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('obtained_date', sa.Date(), nullable=True))
    op.drop_column('certificate', 'obtained_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('obtained_time', sa.DATETIME(), nullable=True))
    op.drop_column('certificate', 'obtained_date')
    # ### end Alembic commands ###
