"""Added mimetype

Revision ID: 6c5811bea6b0
Revises: 816a5001c6a3
Create Date: 2021-09-11 22:00:14.286305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5811bea6b0'
down_revision = '816a5001c6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('cert_img_mimetype', sa.Text(), nullable=True))
    op.add_column('event', sa.Column('logo_mimetype', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'logo_mimetype')
    op.drop_column('certificate', 'cert_img_mimetype')
    # ### end Alembic commands ###
