"""Changed column name

Revision ID: 816a5001c6a3
Revises: 59406947947f
Create Date: 2021-09-11 16:27:45.037177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816a5001c6a3'
down_revision = '59406947947f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_column('certificate', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('certificate', 'title')
    # ### end Alembic commands ###
