"""Added comstraints

Revision ID: c2d2372a13de
Revises: a9a91bf0bac2
Create Date: 2021-09-16 19:57:58.298312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d2372a13de'
down_revision = 'a9a91bf0bac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_certificate_slug', table_name='certificate')
    op.create_index(op.f('ix_certificate_slug'), 'certificate', ['slug'], unique=True)
    op.drop_index('ix_event_slug', table_name='event')
    op.create_index(op.f('ix_event_slug'), 'event', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_slug'), table_name='event')
    op.create_index('ix_event_slug', 'event', ['slug'], unique=False)
    op.drop_index(op.f('ix_certificate_slug'), table_name='certificate')
    op.create_index('ix_certificate_slug', 'certificate', ['slug'], unique=False)
    # ### end Alembic commands ###
