"""Added cert_type column

Revision ID: df8132910da7
Revises: 716c5ecc5f6e
Create Date: 2021-09-12 13:52:09.368107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8132910da7'
down_revision = '716c5ecc5f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('cert_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate', 'cert_type')
    # ### end Alembic commands ###
