# Generated by Django 3.2.7 on 2021-09-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='test', upload_to='images'),
            preserve_default=False,
        ),
    ]
